steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/Sarthak2116/spinnaker"]
    env: ["PROJECT_ROOT=github.com/Sarthak2116/spinnaker"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/linear-quasar-233321/spinnaker:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/{GCP_PROJECT_ID}/spinnaker:$REVISION_ID"
